# .koyeb/app.yaml - Koyeb deployment configuration
name: youtube-automation
services:
  - name: youtube-bot
    type: web
    instance_type: nano
    regions:
      - was
    build:
      type: buildpack
      buildpack: nodejs
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    scaling:
      min: 1
      max: 1
    health_check:
      path: /health
      port: 3000
      initial_delay: 30
      interval: 30
      timeout: 10
      restart_limit: 3
    routes:
      - path: /
        port: 3000

---
# Alternative: docker deployment
name: youtube-automation-docker
services:
  - name: youtube-bot
    type: web
    instance_type: nano
    regions:
      - was
    build:
      type: docker
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
